#
# Copyright 2021 Hewlett Packard Enterprise Development LP
#
# Default values for cray-metrics-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
image:
  repository: k8s.gcr.io/metrics-server
  # tag defaults to chart appVersion
  pullPolicy: Always

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["all"]
  readOnlyRootFilesystem: true
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
